### ISSUE TITLE
Anonymisering av personer som har sluttet

### ISSUE THREAD

**Issue by torjohannessen** [knowit/kompetansekartlegging-app#100]
**Er funksjonaliteten relatert til et problem? Vennligst utdyp.**
Vi ønsker at personer som har sluttet blir annonymisert slik at vi har dataene i behold til bruk i for statistikk og trender innen kompetanse, for eksempel i folk-appen.

**Beskriv løsningen du ønsker**
* Som første løsning ønskes det en MVP hvor en person blir anonymisert av en admin. Admin får en liste av brukere de kan velge å anonymisere.
* Personens id må erstattes, og annen sensitiv informasjon må anonymiseres ved å erstatte verdier i databasen med f.eks. `null`.
* Ett flagg/attributt burde bli satt når brukeren er anonymisert, slik at man kan filtrere ut kompetanse vi har/ikke lengre har. 
* Cognito-brukeren må slettes.
* Logger burde ha en levetid på f.eks. 3 måneder. 
* For å kunne aggregere data burde det også eksistere et felt om når personen ble anonymisert. Derfor burde flere brukere bli anonymisert samtidig innen et tidsrom, og ikke individuelt slik at de kan identifiseres. 

Foreløbige deloppgaver:
- [x] Lag frontend under (f.eks.) Admin -> Anonymiser brukere, der alle brukere i organisasjonen kan anonymiseres
- [x] Cognito-brukeren må slettes - Dette kan gjøres umiddelbart siden kopling til svar/gruppe osv bevares i DynamoDB. 
- [x] Sett levetid på AWS-logger til 3 måneder (spesielt viktig for `kompetansebatchuserform`, og muligens andre)
- [x] DynamoDB
  - [x] Opprett ny tabell `anonymizedUsers` med feltene `id`, `organizationID`, `organization` og `lastAnswerAt`
  - [x] Sett `id`-verdien til å bli en random verdi, slik at brukeren ikke lenger er identifiserbar. Hashing er ikke tilstrekkelig.
  - [x] Lag item i `anonymizedUsers`-tabellen
  - [x] Erstatt `UserForm.owner` og `QuestionAnswer.owner` med ny id (samme id som i `anonymizedUsers`)
  - [x] Slett item i User-tabellen
  - [x] Bruk siste`UserForm.updatedAt` som anonymiseringstidspunkt (lastAnswerAt) i `AnonymizedUser`-tabellen.
- [x] ExternalAPI:
  - [x] `/users`: boolean `includeAnonymized` som sier om anonymiserte brukere skal inkluderes. Kanskje på samme format som aktive brukere (pluss et felt som sier at brukeren er anonymisert?):
  `{"username": "mail@knowit.no","attributes": [{"Name": "email", "Value": "mail@knowit.no"}]},`
  - [x] `/answers`: boolean `includeAnonymized` som sier om svarene til anonymiserte brukere skal inkluderes
- [x] Test anonymiseringen med kode
- [x] Avgjør hvordan man skal fullføre anonymisering dersom det delvis fullføres med feil. 

**Beskriv eventuelle alternativer du har vurdert**
På sikt ønskes det at prosessen _delvis_ automatiseres. For eksempel ved at listen av brukere som kan anonymiseres blir hentet fra AD. Det kan også utføres automatisk anonymisering, men etter en viss tidsperiode siden anonymiseringen ikke er reversibel.

**Comment by synnovsh** [comment]
> For å kunne aggregere data burde det også eksistere et felt om når personen ble anonymisert. Derfor burde flere brukere bli anonymisert samtidig innen et tidsrom, og ikke individuelt slik at de kan identifiseres.

* Dette er noe som må tenkes på. Hva om kun 1 person slutter i det tidsrommet?
  * Dette er teknisk sett et “lenkende” element.
    * [https://www.datatilsynet.no/en/regulations-and-tools/reports-on-specific-subjects/anonymisation/?print=true](https://www.datatilsynet.no/en/regulations-and-tools/reports-on-specific-subjects/anonymisation/?print=true)
* En løsning er da at man ser innen det tidsrommet om det kun er én person som har sluttet. Da kan vi ikke beholde den dataen, eller så må det batches inn i neste “runde” av personer.

**Comment by krisstam** [comment]
> Per nå er det slik at items i DynamoDB-tabellen `User` først opprettes når en (Cognito-)bruker legges til i en gruppeleder-gruppe, og slettes når brukeren fjernes fra gruppa (se [addUserToGroup og removeUserFromGroup](https://github.com/knowit/kompetansekartlegging-app/blob/main/frontend/src/components/AdminPanel/groupsApi.ts)). `User`-tabellen handler altså kun om gruppestruktur, så det er mulig vi må endre slagplan.
> 
> Alternativer:
> 
> 1. Endre på `User`-tabellen slik at items beholdes når brukere fjernes fra gruppe. Så anonymisere denne som planlagt. Problemet er at det blir flere sannhetskilder når det gjelder brukere (DynamoDB og Cognito - se neste punkt).
> 2. Cognito er det som brukes i externalAPI for å hente brukere og deres svar (se `"/users"` og `"/answers"` i [externalApi](https://github.com/knowit/kompetansekartlegging-app/blob/main/cdk/backend/function/externalAPI/app.js) og evt.  [Dataplattform ingestor](https://github.com/knowit/Dataplattform/tree/main/services/ingestion/kompetanseKartlegging/lib/kompetansekartlegging)). Det er derfor en tanke å legge til attributtet `isAnonymized` (eller kanskje heller bare `anonymizedAt`?) og hashe e-posten på cognito-brukeren slik at denne kan knyttes til svar (`Userform`) i DynamoDB. `User` i DynamoDB kan slettes. EDIT: Man kan ikke endre `username` i Cognito, så blir eventuelt å slette Cognito-brukeren og lage en ny.

Ja, det er jo dette som blir problematikken da... User-tabellen i DynamoDB brukes, som du nevner, bare for å holde på gruppetilhørigheten til brukeren, mens Cognito-brukeren blir brukt for alt annet. Vi blir nødt til å slette Cognito-brukeren, ettersom at e-posten er brukernavnet.

Jeg er litt usikker på hva som blir den beste løsningen for anonymiserte brukere. Fra mitt synspunkt så finnes det to løsninger, den ene er å lage en tabell over anonymiserte brukere, hvor du kun har den anonymiserte ID-en og organisasjons-IDen, eller at vi lager anonymiserte brukere i Cognito (Da må vi nok også introdusere en custom-attribute som er "isAnonymized"). Uansett hva vi gjør, så blir det endringer i externalAPI m.m. 

Det som er fint med DynamoDB-tabellen, er at anonymiserte brukere ikke lenger eksisterer i Cognito, og må derfor ikke bli tatt hensyn til i adminQueries eller liknende, men det er mulig det blir noe mer knot et annet sted 😅
