### ISSUE TITLE
Frontend-endring på endring av eksisterende spørsmål

### ISSUE THREAD

**Issue by andersrebner** [knowit/kompetansekartlegging-app#111]
**Beskriv feilen**
Det ser ut som at man kan endre spørsmålstype for eksisterende spørsmål, men det er ikke mulig (og skal ikke være mulig).
Radio buttons vises, men det skjer ikke noe når man trykker på dem fordi knappene er disabled i [QuestionListItemEdit.tsx](https://github.com/knowit/kompetansekartlegging-app/blob/main/frontend/src/components/AdminPanel/EditCatalogs/QuestionListItemEdit.tsx).

Oppgaven innebærer å endre utseendet på spørsmålstype-seksjonen (for eksisterende spørsmål),
slik at man ikke får inntrykk av at det er mulig å endre spørsmålstype.
Hvordan det gjøres er opp til deg, men radio buttons bør kanskje unngås.

**Hvordan reprodusere feil**
1. Applikasjonen må være deployet til sandbox
2. Lag en admin-bruker (kjør [add_admin_user_to_org](https://github.com/knowit/kompetansekartlegging-app/blob/main/scripts/add_admin_user_to_org.py)-scriptet - epost og passord er hardkodet i scriptet)
3. Admin -> Rediger kataloger -> Endre katalog -> Velg en kategori -> Rediger spørsmål (blyant)
4. Forsøk å endre spørsmålstype

**Forventet oppførsel**
Brukeren bør ikke bli "lurt" til å tro at det er mulig å endre spørsmålstype på eksisterende spørsmål.

**Ekstra kontekst**
<img width="562" alt="Screenshot 2023-03-07 at 14 44 06" src="https://user-images.githubusercontent.com/72893130/223440317-7a707f37-a2cb-44b7-be83-01adaabeab34.png">

**Comment by synnovsh** [comment]
NB: epost ikke hardkodet og skriptet kjører med parametre gitt i koden
