### ISSUE TITLE
Bytte fra CRA/react-scripts i frontend

### ISSUE THREAD

**Issue by synnovsh** [knowit/kompetansekartlegging-app#142]
**Er funksjonaliteten relatert til et problem? Vennligst utdyp.**
Per i dag bruker prosjektet CRA og react-scripts som ser ut til å være ganske [døende](https://github.com/reactjs/react.dev/pull/5487#issuecomment-1409720741). Dette er et problem siden det hindrer oppgradering av React, Webpack og moduler og reduserer sikkerhet.   

**Beskriv løsningen du ønsker**
Migrering bort ifra CRA krever at vi bestemmer oss for et alternativ. Spørsmålet er i grunn om vi ønsker å bruke ett nytt rammeverk som Next.js eller å gå bort ifra dette og bruke en bundler som Parcel/Vite.

**Comment by krisstam** [comment]
Ja, vi kan godt bevege oss vekk fra CRA og react-script. Jeg lener mer mot det å bruke en bundler som Vite selv, men dette kan det godt være en diskusjon på. Jeg ser for meg at det blir mindre omskriving dersom vi benytter oss av Vite.

Nextjs er sikkert veldig nice det, men siden vi stort sett skriver backend koden vår i lambdaer og kjører den i AWS sine services, så er jeg usikker på om det er nødvendig for oss. Men her stiller jeg litt svakt, for jeg har ikke vært borte i det enda.
